site_name: Cloud Computing Project Docs
strict: true

theme:
  name: material

docs_dir: docs

nav:
  - Home: service/init_document/ko/init_document.md
  - 서비스 소개:
      - 초기 문서 (KO): service/init_document/ko/init_document.md
      - Initial Document (EN): service/init_document/en/init_document.md
  - Crawler:
      - Overview (EN): service/crawler/en/overview.md
      - Endpoints (EN): service/crawler/en/endpoints.md
      - Data Contracts (EN): service/crawler/en/data-contracts.md
      - 개요 (KO): service/crawler/ko/overview.md
      - 엔드포인트 (KO): service/crawler/ko/endpoints.md
      - 데이터 계약 (KO): service/crawler/ko/data-contracts.md
  - News Crawling Service:
      - English: service/news-crawling-service/en/news-crawling-service.md
      - 한국어: service/news-crawling-service/ko/news-crawling-service.md
  - News Keyword Service:
      - English: service/news-keyword-service/en/news-keyword-service.md
      - 한국어: service/news-keyword-service/ko/news-keyword-service.md
  - News Sentiment Service:
      - English: service/news-sentiment-service/en/news-sentiment-service.md
      - 한국어: service/news-sentiment-service/ko/news-sentiment-service.md
